services:
  server:
    build: ./server
    ports:
      - "5001:5001"
    depends_on:
      - mongo
  api:
    build:
      context: ./api
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:

